### ISSUE TITLE
Update various classpath issues and maven dependencies for migration to Java 9+

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#157]
Currently, due to the move to the module system in Java 9, findbugs complains of:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (..../repository/org/codehaus/groovy/groovy-all/2.4.0/groovy-all-2.4.0.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

and when testing RestResourceServiceIT the following failure occurs: 
uk.gov.gchq.palisade.resource.service.impl.RestResourceServiceV1IT  Time elapsed: 0.658 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:270)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)

**Comment by m09526** [comment]
Findbugs no longer supported
